#!/bin/sh

set -e

lb config noauto \
    --architectures	                    "amd64" \
    --distribution 	                    "bullseye" \
    --linux-packages	                "linux-image-5.17.0-haswell linux-headers-5.17.0-haswell" \
    --firmware-binary                   false \
    --firmware-chroot                   false \
    --bootappend-live 	                "boot=live" \
    --bootappend-install                "" \
    --archive-areas 	                "main contrib non-free" \
    --memtest                           "memtest86+" \
    --bootloaders                       "grub-efi" \
    --chroot-squashfs-compression-type  "zstd" \
    --debian-installer 	                "live" \
    --security                          true  \
    --updates                           true  \
    --backports                         true  \
    --debian-installer-gui              true  \
    --win32-loader	                    false \
	--binary-images                     'iso-hybrid' \
	--iso-volume                        'Debian_For_Latitude3550' \
	--iso-application                   'Debian for Latitude3550' \
	--iso-preparer                      'SoftReaper' \
	--iso-publisher                     'SoftReaper@gmail.com' \
    --verbose
    "${@}"
